name: Frontend CD

on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Execute Remote SSH Commands Using Password
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: "37.44.244.171"
      #     username: "root"
      #     password: "@DANgand123"
      #     port: "22"
      #     script: |
      #       cd ~/project/dangand_v2
      #       git checkout main
      #       git pull origin main
      #       curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      #       export NVM_DIR="$HOME/.nvm"
      #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      #       nvm install 16
      #       nvm use 16
      #       yarn
      #       pm2 stop all
      #       yarn build
      #       pm2 reload all
      #       pm2 restart all
      #       sudo service nginx restart

      - name: Checkout kode
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.0-rc.1"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Kirim Notifikasi ke Telegram
        run: |
          TELEGRAM_BOT_TOKEN=6022708597:AAFBHWHOd0CydmP4unyBe_jVUfaJ6c0o6eU
          CHAT_ID=-1001488314590
          MESSAGE="
          FRONTEND DEPLOY SUCCESS
          _________________________

          - platform: Dangand web
          - type: production
          - type: production
          - branch: main
          - version: 2.0.1
          - url: https://dangand.com

          deploy script by:@rianllauo"

          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$CHAT_ID -d message_thread_id: 5, -d text="$MESSAGE"
