name: Frontend CD

on:
  push:
    branches: [development]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Remote SSH Commands Using Password
        uses: appleboy/ssh-action@master
        with:
          host: "37.44.244.171" # Ganti dengan alamat IP VPS Anda
          username: "root" # Ganti dengan username SSH VPS Anda
          password: "@DANgand123" # Ganti dengan password SSH VPS Anda
          port: "22" # Ganti dengan port SSH yang digunakan pada VPS Anda
          script: |
            cd ~/project/sandbox
            git checkout development
            git pull origin development
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 16
            nvm use 16
            yarn
            pm2 stop all
            yarn build
            pm2 start all
            sudo service nginx restart

      # - name: Send Telegram Notification
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     socks5: "socks5://67.207.92.96:1466"
      #     message: |
      #       ${{ github.actor }} created commit:
      #       Commit message: ${{ github.event.commits[0].message }}

      #       Repository: ${{ github.repository }}

      #       See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
