name: Telegram Notify

on:
  push:
    branches: [main, development, production]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify the commit on Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: "6022708597:AAFBHWHOd0CydmP4unyBe_jVUfaJ6c0o6eU"
          chat_id: "-1001488314590"
          topic_id: "5"
